### ISSUE TITLE
Root permission granting is not properly handled

### ISSUE THREAD

**Issue by aviraxp** [topjohnwu/MagiskManager#149] opened 2017-04-18 11:54 UTC
Sometimes, when I uninstall an app, it is not removed from the database, so if other apps are installed and use the same identity symbol (UID?), it will be automatically granted root access.

**Comment by aviraxp** [comment] 2017-04-18 12:00
Seems this will happen when installing application with same package name but different name.

**Comment by Didgeridoohan** [comment] 2017-05-07 10:05
I saw this today where [Root Checker](https://play.google.com/store/apps/details?id=com.joeykrim.rootcheck) was granted superuser access without prompting for it. The toast stated that [GSAM Battery Monitor](https://play.google.com/store/apps/details?id=com.gsamlabs.bbm) was granted superuser access, an app that I currently do not have on my device (but have granted superuser access previously)...

I did some testing (installing - granting root - uninstalling, etc) to see if I could repeat the issue, but no dice and therefore no logs. :(

Magisk v12, Magisk Manager 4.3.3.

**Comment by topjohnwu** [comment] 2017-05-08 03:56
@Didgeridoohan I might know the issue, I would find a way to fix it. The bug is caused by Android recycling the UID for apps. There is however, a way to fix it. Thanks for reporting

**Comment by topjohnwu** [comment] 2017-05-31 08:32
Fixed in 29096eb5d7ca76c45046d1f6aad8bbe98c7201bf

**Closed by topjohnwu** 2017-05-31 08:32 UTC
